export const VISUAL_SCENARIO_IDS = {
  badge: 'visual/badge',
  badgeDot: 'visual/badge-dot',
  button: 'visual/button',
  checkBox: 'visual/check-box',
  divider: 'visual/divider',
  fieldSet: 'visual/field-set',
  input: 'visual/input',
  link: 'visual/link',
  list: 'visual/list',
  progressHeader: 'visual/progress-header',
  progressPage: 'visual/progress-page',
  pulse: 'visual/pulse',
  radioButton: 'visual/radio-button',
  removableChip: 'visual/removable-chip',
  selectableChip: 'visual/selectable-chip',
  skeleton: 'visual/skeleton',
  spinner: 'visual/spinner',
  toggle: 'visual/toggle',
} as const;
