export const VISUAL_SCENARIO_IDS = {
  badge: 'visual/badge',
  badgeDot: 'visual/badge-dot',
  button: 'visual/button',
  checkBox: 'visual/check-box',
  chips: 'visual/chips',
  divider: 'visual/divider',
  fieldSet: 'visual/field-set',
  input: 'visual/input',
  link: 'visual/link',
  list: 'visual/list',
  pills: 'visual/pills',
  progressHeader: 'visual/progress-header',
  progressPage: 'visual/progress-page',
  pulse: 'visual/pulse',
  radioButton: 'visual/radio-button',
  skeleton: 'visual/skeleton',
  spinner: 'visual/spinner',
  toggle: 'visual/toggle',
} as const;
