export const PROGRESS_PAGE_VALUE_PROPERTY = '--admiral-progress-page-value';

export const PROGRESS_PAGE_APPEARANCES = ['primary'] as const;

export const PROGRESS_PAGE_MIN_WIDTH = 140;
export const PROGRESS_PAGE_HEIGHT = 4;
export const PROGRESS_PAGE_BORDER_RADIUS = 2;

export const PROGRESS_PAGE_INDETERMINATE_ANIMATION_DURATION = '1400ms';
export const PROGRESS_PAGE_INDETERMINATE_INDICATOR_WIDTH = 40;
export const PROGRESS_PAGE_INDETERMINATE_TRANSLATE_END = (100 / PROGRESS_PAGE_INDETERMINATE_INDICATOR_WIDTH) * 100;
export const PROGRESS_PAGE_INDETERMINATE_TRANSLATE_CENTER =
  ((100 - PROGRESS_PAGE_INDETERMINATE_INDICATOR_WIDTH) / 2 / PROGRESS_PAGE_INDETERMINATE_INDICATOR_WIDTH) * 100;
