import {
  SELECTION_CONTROL_INPUT_DIMENSIONS,
  SELECTION_CONTROL_INPUT_DIMENSION_PARAMETERS,
} from '../_internal/InputAtoms/constants';

export const CHECK_BOX_DIMENSIONS = SELECTION_CONTROL_INPUT_DIMENSIONS;
export const CHECK_BOX_DIMENSION_PARAMETERS = SELECTION_CONTROL_INPUT_DIMENSION_PARAMETERS;
