export const PROGRESS_HEADER_VALUE_PROPERTY = '--admiral-progress-header-value';

export const PROGRESS_HEADER_APPEARANCES = ['primary'] as const;

export const PROGRESS_HEADER_HEIGHT = 4;
export const PROGRESS_HEADER_INDETERMINATE_ANIMATION_DURATION = '1400ms';
export const PROGRESS_HEADER_INDETERMINATE_INDICATOR_WIDTH = 40;
export const PROGRESS_HEADER_INDETERMINATE_TRANSLATE_END = (100 / PROGRESS_HEADER_INDETERMINATE_INDICATOR_WIDTH) * 100;
export const PROGRESS_HEADER_INDETERMINATE_TRANSLATE_CENTER =
  ((100 - PROGRESS_HEADER_INDETERMINATE_INDICATOR_WIDTH) / 2 / PROGRESS_HEADER_INDETERMINATE_INDICATOR_WIDTH) * 100;
